name: Release

# This GitHub action creates a release when a tag is created.
on:
  push:
    tags:
      - '*'

permissions:
  # Write is needed to create a new release on the repo
  contents: write
  # For uploading to Github Docker Registry
  packages: write
  # Both for attesting the docker image
  id-token: write
  attestations: write

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux"]
        arch: ["386", "amd64", "arm-7", "arm64"]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - name: Setup just command runner
        uses: taiki-e/install-action@6f9c7cc51aa54b13cbcbd12f8bbf69d8ba405b4b # v2.62.47
        with:
          tool: just@1.42.4
      - name: Build in Container
        run: just build ${{matrix.arch}} ${{matrix.os}}
      - name: Archive build artifacts
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: plugin-${{ matrix.os }}-${{ matrix.arch }}
          path: _build/*-${{ matrix.os }}-${{ matrix.arch }}.so
      - name: Output server version
        id: server_version
        run: echo "ver=$(cat SERVER_VERSION.txt)" >> "$GITHUB_OUTPUT"
    outputs:
      server_version: ${{ steps.server_version.outputs.ver }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          artifacts: "plugin-*/*.so"
          generateReleaseNotes: true
          body: |
            **Comaptible with [gotify/server](https://github.com/gotify/server) version `${{ needs.build.outputs.server_version }}`**

            See the [Readme](https://github.com/LukasKnuth/gotify-slack-webhook#setup) for setup instructions.

  bundle-container:
    needs: build
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: lukasknuth/gotify-slack-webhook-bundled
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      - name: Move build output into shared folder
        run: |
          ls -R
          mkdir out
          mv plugin-*/*.so out/
      - name: Rename ARMv7 plugin so Docker finds it
        # NOTE: `docker buildx` differentiates by Arch only (amd64/arm64/arm), not variant (v7)
        run: mv out/gotify-slack-webhook-linux-arm-7.so out/gotify-slack-webhook-linux-arm.so
      - uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Generate Container Metadata from git
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@4f7cdeb0f05278b464e71357394bf2c61f94138e # v6.6.0
        id: push
        with:
          context: .
          file: bundle.Dockerfile
          push: true
          # NOTE: 386 missing because there is no official image.
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: actions/attest-build-provenance@310b0a4a3b0b78ef57ecda988ee04b132db73ef8 # v1.4.1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
